version: 2

project_name: vendel-android

builds:
  - skip: true

release:
  github:
    owner: JimScope
    name: vendel-android
  draft: false
  prerelease: auto
  name_template: "Vendel v{{ .Version }}"

extra_files:
  - glob: app/build/outputs/apk/release/app-universal-release.apk
    name_template: "vendel-v{{ .Version }}-universal.apk"
  - glob: app/build/outputs/apk/release/app-arm64-v8a-release.apk
    name_template: "vendel-v{{ .Version }}-arm64-v8a.apk"
  - glob: app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    name_template: "vendel-v{{ .Version }}-armeabi-v7a.apk"
  - glob: app/build/outputs/apk/release/app-x86_64-release.apk
    name_template: "vendel-v{{ .Version }}-x86_64.apk"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
      - "^chore:"
